"""empty message

Revision ID: 10959332b248
Revises: 
Create Date: 2026-05-08 16:55:40.112356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10959332b248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emial', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('emial', name=op.f('uq_user_emial_key'))
    )
    op.create_table('vegetable_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vegetable_category'))
    )
    op.create_table('vegetable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('pub_time', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vegetable_category.id'], name=op.f('fk_vegetable_category_id_vegetable_category')),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], name=op.f('fk_vegetable_publisher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vegetable'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetable')
    op.drop_table('vegetable_category')
    op.drop_table('user')
    # ### end Alembic commands ###
