"""rename emial to email

Revision ID: 5345d3e1ff75
Revises: 870da08ad13b
Create Date: 2026-06-05 16:30:49.715267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5345d3e1ff75'
down_revision = '870da08ad13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_user_emial_key'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email_key'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('uq_user_emial_key'), ['email'], unique=True)

    # ### end Alembic commands ###
