"""empty message

Revision ID: 870da08ad13b
Revises: f9a605c366e9
Create Date: 2026-05-16 21:26:07.757392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870da08ad13b'
down_revision = 'f9a605c366e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_email_code_email_key'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_email_code_email_key'), ['email'], unique=True)

    # ### end Alembic commands ###
